# Modifying Dataframe

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pld
import seaborn as sns

## Dropping Columns

> To drop a column, there are two ways:

Syntax: 
    1. df.drop(labels=[["x","y","z"],axis=1)
        axis can be typed 1 or 'columns', 
        both have same result
      
    2. df.drop(columns=["x","y","z"])
        this also drops those three columns and prints the new dataframe
        
    By default, this change is not permanent.

In [5]:
coin = pd.read_csv("coin_Bitcoin.csv").head()
coin

,SNo,Name,Symbol,Date,Month,Year,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,4/29/2013 23:59,4,2013,147.49,134.00,134.44,144.54,0,1603768865
1,2,Bitcoin,BTC,4/30/2013 23:59,4,2013,146.93,134.05,144.00,139.00,0,1542813125
2,3,Bitcoin,BTC,5/1/2013 23:59,5,2013,139.89,107.72,139.00,116.99,0,1298954594
3,4,Bitcoin,BTC,5/2/2013 23:59,5,2013,125.60,92.28,116.38,105.21,0,1168517495
4,5,Bitcoin,BTC,5/3/2013 23:59,5,2013,108.13,79.10,106.25,97.75,0,1085995169

In [6]:
coin.drop(columns=["Date","High","Low"])

   SNo     Name Symbol  Month  Year    Open   Close  Volume   Marketcap
0    1  Bitcoin    BTC      4  2013  134.44  144.54       0  1603768865
1    2  Bitcoin    BTC      4  2013  144.00  139.00       0  1542813125
2    3  Bitcoin    BTC      5  2013  139.00  116.99       0  1298954594
3    4  Bitcoin    BTC      5  2013  116.38  105.21       0  1168517495
4    5  Bitcoin    BTC      5  2013  106.25   97.75       0  1085995169

## Dropping Rows

Syntax:
    > df.drop(labels=["x","y","z"],axis=0)
        This drops rows and labels/index.
    > Two by default, axis = 0
        we can also ignore putting axis = 0

In [10]:
countries = pd.read_csv("world-happiness-report-2021.csv").set_index("Country name")
c_to_i = countries.loc["China":"India"]
c_to_i

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
China,East Asia,5.339,0.029,5.397,5.281,9.673,0.811,69.593,0.904,-0.146,0.755,2.43,1.061,0.785,0.665,0.636,0.093,0.117,1.982
Ivory Coast,Sub-Saharan Africa,5.306,0.078,5.460,5.152,8.551,0.644,50.114,0.741,-0.016,0.794,2.43,0.669,0.409,0.052,0.438,0.177,0.092,3.469
Armenia,Commonwealth of Independent States,5.283,0.058,5.397,5.168,9.487,0.799,67.055,0.825,-0.168,0.629,2.43,0.996,0.758,0.585,0.540,0.079,0.198,2.127
Nepal,South Asia,5.269,0.070,5.406,5.132,8.120,0.774,64.233,0.782,0.152,0.727,2.43,0.519,0.702,0.496,0.488,0.287,0.135,2.642
Bulgaria,Central and Eastern Europe,5.266,0.054,5.371,5.160,10.016,0.931,67.000,0.788,-0.096,0.932,2.43,1.181,1.055,0.583,0.494,0.125,0.005,1.823
Maldives,South Asia,5.198,0.072,5.339,5.057,9.826,0.913,70.600,0.854,0.024,0.825,2.43,1.115,1.015,0.697,0.575,0.204,0.073,1.520
Azerbaijan,Commonwealth of Independent States,5.171,0.040,5.250,5.091,9.569,0.836,65.656,0.814,-0.223,0.506,2.43,1.025,0.841,0.541,0.526,0.043,0.276,1.919
Cameroon,Sub-Saharan Africa,5.142,0.074,5.288,4.996,8.189,0.710,53.515,0.731,0.026,0.848,2.43,0.543,0.556,0.159,0.425,0.205,0.058,3.195
Senegal,Sub-Saharan Africa,5.132,0.068,5.266,4.998,8.118,0.710,59.802,0.695,-0.046,0.801,2.43,0.518,0.558,0.357,0.381,0.158,0.088,3.071
Albania,Central and Eastern Europe,5.117,0.059,5.234,5.001,9.520,0.697,68.999,0.785,-0.030,0.901,2.43,1.008,0.529,0.646,0.491,0.168,0.024,2.250
North Macedonia,Central and Eastern Europe,5.101,0.051,5.202,5.001,9.693,0.805,65.474,0.751,0.038,0.905,2.43,1.068,0.772,0.535,0.450,0.212,0.022,2.042
Ghana,Sub-Saharan Africa,5.088,0.067,5.219,4.958,8.580,0.727,57.586,0.807,0.123,0.848,2.43,0.680,0.595,0.287,0.517,0.268,0.058,2.684
Niger,Sub-Saharan Africa,5.074,0.102,5.273,4.875,7.098,0.641,53.780,0.806,0.018,0.693,2.43,0.162,0.402,0.167,0.516,0.200,0.157,3.470
Turkmenistan,Commonwealth of Independent States,5.066,0.036,5.136,4.996,9.629,0.983,62.409,0.877,0.273,0.888,2.43,1.046,1.172,0.439,0.602,0.366,0.033,1.409
Gambia,Sub-Saharan Africa,5.051,0.089,5.225,4.877,7.686,0.690,55.160,0.697,0.424,0.746,2.43,0.367,0.511,0.210,0.384,0.465,0.123,2.990
Benin,Sub-Saharan Africa,5.045,0.073,5.189,4.901,8.087,0.489,54.713,0.757,-0.034,0.661,2.43,0.507,0.058,0.196,0.457,0.166,0.178,3.482
Laos,Southeast Asia,5.030,0.045,5.119,4.941,8.947,0.728,58.968,0.910,0.123,0.658,2.43,0.808,0.598,0.330,0.643,0.268,0.179,2.204
Bangladesh,South Asia,5.025,0.046,5.115,4.934,8.454,0.693,64.800,0.877,-0.041,0.682,2.43,0.635,0.520,0.514,0.603,0.161,0.164,2.427
Guinea,Sub-Saharan Africa,4.984,0.090,5.160,4.808,7.838,0.639,55.008,0.697,0.095,0.766,2.43,0.420,0.399,0.206,0.384,0.250,0.111,3.216
South Africa,Sub-Saharan Africa,4.956,0.060,5.074,4.839,9.403,0.860,56.904,0.749,-0.067,0.860,2.43,0.967,0.895,0.265,0.447,0.144,0.051,2.187
Turkey,Middle East and North Africa,4.948,0.046,5.038,4.857,10.240,0.822,67.199,0.576,-0.139,0.776,2.43,1.260,0.809,0.590,0.236,0.097,0.104,1.852
Pakistan,South Asia,4.934,0.068,5.066,4.802,8.458,0.651,58.709,0.726,0.098,0.787,2.43,0.637,0.423,0.322,0.418,0.252,0.097,2.784
Morocco,Middle East and North Africa,4.918,0.060,5.036,4.800,8.903,0.560,66.208,0.774,-0.236,0.801,2.43,0.792,0.219,0.558,0.477,0.034,0.088,2.749
Venezuela,Latin America and Caribbean,4.892,0.064,5.017,4.767,9.073,0.861,66.700,0.615,-0.169,0.827,2.43,0.852,0.897,0.574,0.284,0.078,0.072,2.135
Georgia,Commonwealth of Independent States,4.891,0.054,4.998,4.785,9.585,0.671,64.300,0.783,-0.238,0.655,2.43,1.030,0.470,0.498,0.488,0.032,0.181,2.191
Algeria,Middle East and North Africa,4.887,0.053,4.991,4.783,9.342,0.802,66.005,0.480,-0.067,0.752,2.43,0.946,0.765,0.552,0.119,0.144,0.120,2.242
Ukraine,Commonwealth of Independent States,4.875,0.052,4.977,4.773,9.436,0.888,64.902,0.724,-0.011,0.924,2.43,0.979,0.958,0.517,0.417,0.181,0.010,1.813
Iraq,Middle East and North Africa,4.854,0.059,4.970,4.738,9.240,0.746,60.583,0.630,-0.053,0.875,2.43,0.910,0.638,0.381,0.302,0.153,0.041,2.429
Gabon,Sub-Saharan Africa,4.852,0.075,4.998,4.706,9.603,0.776,59.962,0.731,-0.200,0.840,2.43,1.037,0.707,0.362,0.424,0.058,0.064,2.201
Burkina Faso,Sub-Saharan Africa,4.834,0.081,4.993,4.675,7.678,0.672,54.151,0.695,-0.009,0.748,2.43,0.364,0.472,0.179,0.381,0.182,0.122,3.133
Cambodia,Southeast Asia,4.830,0.067,4.963,4.698,8.360,0.765,62.000,0.959,0.034,0.843,2.43,0.603,0.680,0.426,0.702,0.210,0.061,2.148
Mozambique,Sub-Saharan Africa,4.794,0.103,4.997,4.592,7.158,0.744,54.706,0.882,0.061,0.684,2.43,0.183,0.634,0.196,0.608,0.228,0.163,2.783
Nigeria,Sub-Saharan Africa,4.759,0.052,4.861,4.658,8.533,0.740,50.102,0.737,0.037,0.878,2.43,0.663,0.625,0.051,0.433,0.212,0.039,2.736
Mali,Sub-Saharan Africa,4.723,0.082,4.884,4.563,7.744,0.724,51.969,0.697,-0.036,0.827,2.43,0.387,0.590,0.110,0.384,0.164,0.072,3.016
Iran,Middle East and North Africa,4.721,0.055,4.828,4.614,9.584,0.710,66.300,0.608,0.218,0.714,2.43,1.030,0.557,0.561,0.275,0.330,0.144,1.823
Uganda,Sub-Saharan Africa,4.636,0.073,4.780,4.493,7.677,0.781,56.101,0.709,0.122,0.855,2.43,0.364,0.718,0.240,0.398,0.267,0.054,2.596
Liberia,Sub-Saharan Africa,4.625,0.106,4.833,4.417,7.288,0.720,56.498,0.735,0.050,0.850,2.43,0.228,0.580,0.253,0.430,0.221,0.057,2.857
Kenya,Sub-Saharan Africa,4.607,0.072,4.747,4.466,8.361,0.688,60.704,0.779,0.287,0.825,2.43,0.603,0.508,0.385,0.483,0.375,0.073,2.180
Tunisia,Middle East and North Africa,4.596,0.058,4.709,4.484,9.266,0.691,67.201,0.656,-0.201,0.870,2.43,0.919,0.515,0.590,0.334,0.057,0.044,2.138
Lebanon,Middle East and North Africa,4.584,0.055,4.691,4.477,9.626,0.848,67.355,0.525,-0.073,0.898,2.43,1.045,0.868,0.595,0.175,0.140,0.026,1.736
Namibia,Sub-Saharan Africa,4.574,0.064,4.700,4.448,9.161,0.818,56.799,0.719,-0.149,0.847,2.43,0.882,0.801,0.262,0.411,0.091,0.059,2.068
Palestinian Territories,Middle East and North Africa,4.517,0.067,4.649,4.384,8.485,0.826,62.250,0.653,-0.163,0.821,2.43,0.646,0.819,0.434,0.330,0.082,0.075,2.131
Myanmar,Southeast Asia,4.426,0.052,4.527,4.324,8.541,0.779,59.302,0.876,0.509,0.660,2.43,0.666,0.713,0.341,0.601,0.520,0.178,1.407
Jordan,Middle East and North Africa,4.395,0.062,4.516,4.273,9.182,0.767,67.000,0.755,-0.167,0.705,2.43,0.890,0.685,0.583,0.455,0.079,0.150,1.553
Chad,Sub-Saharan Africa,4.355,0.094,4.540,4.171,7.364,0.619,48.478,0.579,0.041,0.807,2.43,0.255,0.353,0.000,0.240,0.215,0.084,3.209
Sri Lanka,South Asia,4.325,0.066,4.454,4.196,9.470,0.827,67.299,0.841,0.079,0.863,2.43,0.990,0.820,0.593,0.559,0.239,0.049,1.075
Swaziland,Sub-Saharan Africa,4.308,0.071,4.448,4.168,9.065,0.770,50.833,0.647,-0.185,0.708,2.43,0.849,0.693,0.074,0.323,0.067,0.147,2.155
Comoros,Sub-Saharan Africa,4.289,0.084,4.454,4.123,8.031,0.626,57.349,0.548,0.082,0.781,2.43,0.488,0.367,0.279,0.202,0.241,0.101,2.610
Egypt,Middle East and North Africa,4.283,0.045,4.371,4.195,9.367,0.750,61.998,0.749,-0.182,0.795,2.43,0.954,0.647,0.426,0.446,0.069,0.092,1.648
Ethiopia,Sub-Saharan Africa,4.275,0.051,4.374,4.175,7.694,0.764,59.000,0.752,0.082,0.761,2.43,0.370,0.679,0.331,0.451,0.241,0.114,2.089
Mauritania,Sub-Saharan Africa,4.227,0.070,4.365,4.090,8.542,0.795,57.161,0.561,-0.106,0.731,2.43,0.666,0.749,0.273,0.218,0.119,0.133,2.069
Madagascar,Sub-Saharan Africa,4.208,0.072,4.349,4.068,7.396,0.686,59.305,0.552,-0.005,0.803,2.43,0.266,0.503,0.341,0.207,0.185,0.087,2.620
Togo,Sub-Saharan Africa,4.107,0.077,4.258,3.956,7.362,0.569,54.914,0.619,0.032,0.772,2.43,0.254,0.239,0.203,0.289,0.209,0.107,2.806
Zambia,Sub-Saharan Africa,4.073,0.069,4.209,3.938,8.145,0.708,55.809,0.782,0.061,0.823,2.43,0.528,0.552,0.231,0.487,0.227,0.074,1.975
Sierra Leone,Sub-Saharan Africa,3.849,0.077,4.001,3.698,7.434,0.630,51.651,0.717,0.084,0.866,2.43,0.279,0.377,0.100,0.408,0.243,0.047,2.396
India,South Asia,3.819,0.026,3.869,3.769,8.755,0.603,60.633,0.893,0.089,0.774,2.43,0.741,0.316,0.383,0.622,0.246,0.106,1.405

In [11]:
c_to_i.drop(labels="Armenia")

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
China,East Asia,5.339,0.029,5.397,5.281,9.673,0.811,69.593,0.904,-0.146,0.755,2.43,1.061,0.785,0.665,0.636,0.093,0.117,1.982
Ivory Coast,Sub-Saharan Africa,5.306,0.078,5.460,5.152,8.551,0.644,50.114,0.741,-0.016,0.794,2.43,0.669,0.409,0.052,0.438,0.177,0.092,3.469
Nepal,South Asia,5.269,0.070,5.406,5.132,8.120,0.774,64.233,0.782,0.152,0.727,2.43,0.519,0.702,0.496,0.488,0.287,0.135,2.642
Bulgaria,Central and Eastern Europe,5.266,0.054,5.371,5.160,10.016,0.931,67.000,0.788,-0.096,0.932,2.43,1.181,1.055,0.583,0.494,0.125,0.005,1.823
Maldives,South Asia,5.198,0.072,5.339,5.057,9.826,0.913,70.600,0.854,0.024,0.825,2.43,1.115,1.015,0.697,0.575,0.204,0.073,1.520
Azerbaijan,Commonwealth of Independent States,5.171,0.040,5.250,5.091,9.569,0.836,65.656,0.814,-0.223,0.506,2.43,1.025,0.841,0.541,0.526,0.043,0.276,1.919
Cameroon,Sub-Saharan Africa,5.142,0.074,5.288,4.996,8.189,0.710,53.515,0.731,0.026,0.848,2.43,0.543,0.556,0.159,0.425,0.205,0.058,3.195
Senegal,Sub-Saharan Africa,5.132,0.068,5.266,4.998,8.118,0.710,59.802,0.695,-0.046,0.801,2.43,0.518,0.558,0.357,0.381,0.158,0.088,3.071
Albania,Central and Eastern Europe,5.117,0.059,5.234,5.001,9.520,0.697,68.999,0.785,-0.030,0.901,2.43,1.008,0.529,0.646,0.491,0.168,0.024,2.250
North Macedonia,Central and Eastern Europe,5.101,0.051,5.202,5.001,9.693,0.805,65.474,0.751,0.038,0.905,2.43,1.068,0.772,0.535,0.450,0.212,0.022,2.042
Ghana,Sub-Saharan Africa,5.088,0.067,5.219,4.958,8.580,0.727,57.586,0.807,0.123,0.848,2.43,0.680,0.595,0.287,0.517,0.268,0.058,2.684
Niger,Sub-Saharan Africa,5.074,0.102,5.273,4.875,7.098,0.641,53.780,0.806,0.018,0.693,2.43,0.162,0.402,0.167,0.516,0.200,0.157,3.470
Turkmenistan,Commonwealth of Independent States,5.066,0.036,5.136,4.996,9.629,0.983,62.409,0.877,0.273,0.888,2.43,1.046,1.172,0.439,0.602,0.366,0.033,1.409
Gambia,Sub-Saharan Africa,5.051,0.089,5.225,4.877,7.686,0.690,55.160,0.697,0.424,0.746,2.43,0.367,0.511,0.210,0.384,0.465,0.123,2.990
Benin,Sub-Saharan Africa,5.045,0.073,5.189,4.901,8.087,0.489,54.713,0.757,-0.034,0.661,2.43,0.507,0.058,0.196,0.457,0.166,0.178,3.482
Laos,Southeast Asia,5.030,0.045,5.119,4.941,8.947,0.728,58.968,0.910,0.123,0.658,2.43,0.808,0.598,0.330,0.643,0.268,0.179,2.204
Bangladesh,South Asia,5.025,0.046,5.115,4.934,8.454,0.693,64.800,0.877,-0.041,0.682,2.43,0.635,0.520,0.514,0.603,0.161,0.164,2.427
Guinea,Sub-Saharan Africa,4.984,0.090,5.160,4.808,7.838,0.639,55.008,0.697,0.095,0.766,2.43,0.420,0.399,0.206,0.384,0.250,0.111,3.216
South Africa,Sub-Saharan Africa,4.956,0.060,5.074,4.839,9.403,0.860,56.904,0.749,-0.067,0.860,2.43,0.967,0.895,0.265,0.447,0.144,0.051,2.187
Turkey,Middle East and North Africa,4.948,0.046,5.038,4.857,10.240,0.822,67.199,0.576,-0.139,0.776,2.43,1.260,0.809,0.590,0.236,0.097,0.104,1.852
Pakistan,South Asia,4.934,0.068,5.066,4.802,8.458,0.651,58.709,0.726,0.098,0.787,2.43,0.637,0.423,0.322,0.418,0.252,0.097,2.784
Morocco,Middle East and North Africa,4.918,0.060,5.036,4.800,8.903,0.560,66.208,0.774,-0.236,0.801,2.43,0.792,0.219,0.558,0.477,0.034,0.088,2.749
Venezuela,Latin America and Caribbean,4.892,0.064,5.017,4.767,9.073,0.861,66.700,0.615,-0.169,0.827,2.43,0.852,0.897,0.574,0.284,0.078,0.072,2.135
Georgia,Commonwealth of Independent States,4.891,0.054,4.998,4.785,9.585,0.671,64.300,0.783,-0.238,0.655,2.43,1.030,0.470,0.498,0.488,0.032,0.181,2.191
Algeria,Middle East and North Africa,4.887,0.053,4.991,4.783,9.342,0.802,66.005,0.480,-0.067,0.752,2.43,0.946,0.765,0.552,0.119,0.144,0.120,2.242
Ukraine,Commonwealth of Independent States,4.875,0.052,4.977,4.773,9.436,0.888,64.902,0.724,-0.011,0.924,2.43,0.979,0.958,0.517,0.417,0.181,0.010,1.813
Iraq,Middle East and North Africa,4.854,0.059,4.970,4.738,9.240,0.746,60.583,0.630,-0.053,0.875,2.43,0.910,0.638,0.381,0.302,0.153,0.041,2.429
Gabon,Sub-Saharan Africa,4.852,0.075,4.998,4.706,9.603,0.776,59.962,0.731,-0.200,0.840,2.43,1.037,0.707,0.362,0.424,0.058,0.064,2.201
Burkina Faso,Sub-Saharan Africa,4.834,0.081,4.993,4.675,7.678,0.672,54.151,0.695,-0.009,0.748,2.43,0.364,0.472,0.179,0.381,0.182,0.122,3.133
Cambodia,Southeast Asia,4.830,0.067,4.963,4.698,8.360,0.765,62.000,0.959,0.034,0.843,2.43,0.603,0.680,0.426,0.702,0.210,0.061,2.148
Mozambique,Sub-Saharan Africa,4.794,0.103,4.997,4.592,7.158,0.744,54.706,0.882,0.061,0.684,2.43,0.183,0.634,0.196,0.608,0.228,0.163,2.783
Nigeria,Sub-Saharan Africa,4.759,0.052,4.861,4.658,8.533,0.740,50.102,0.737,0.037,0.878,2.43,0.663,0.625,0.051,0.433,0.212,0.039,2.736
Mali,Sub-Saharan Africa,4.723,0.082,4.884,4.563,7.744,0.724,51.969,0.697,-0.036,0.827,2.43,0.387,0.590,0.110,0.384,0.164,0.072,3.016
Iran,Middle East and North Africa,4.721,0.055,4.828,4.614,9.584,0.710,66.300,0.608,0.218,0.714,2.43,1.030,0.557,0.561,0.275,0.330,0.144,1.823
Uganda,Sub-Saharan Africa,4.636,0.073,4.780,4.493,7.677,0.781,56.101,0.709,0.122,0.855,2.43,0.364,0.718,0.240,0.398,0.267,0.054,2.596
Liberia,Sub-Saharan Africa,4.625,0.106,4.833,4.417,7.288,0.720,56.498,0.735,0.050,0.850,2.43,0.228,0.580,0.253,0.430,0.221,0.057,2.857
Kenya,Sub-Saharan Africa,4.607,0.072,4.747,4.466,8.361,0.688,60.704,0.779,0.287,0.825,2.43,0.603,0.508,0.385,0.483,0.375,0.073,2.180
Tunisia,Middle East and North Africa,4.596,0.058,4.709,4.484,9.266,0.691,67.201,0.656,-0.201,0.870,2.43,0.919,0.515,0.590,0.334,0.057,0.044,2.138
Lebanon,Middle East and North Africa,4.584,0.055,4.691,4.477,9.626,0.848,67.355,0.525,-0.073,0.898,2.43,1.045,0.868,0.595,0.175,0.140,0.026,1.736
Namibia,Sub-Saharan Africa,4.574,0.064,4.700,4.448,9.161,0.818,56.799,0.719,-0.149,0.847,2.43,0.882,0.801,0.262,0.411,0.091,0.059,2.068
Palestinian Territories,Middle East and North Africa,4.517,0.067,4.649,4.384,8.485,0.826,62.250,0.653,-0.163,0.821,2.43,0.646,0.819,0.434,0.330,0.082,0.075,2.131
Myanmar,Southeast Asia,4.426,0.052,4.527,4.324,8.541,0.779,59.302,0.876,0.509,0.660,2.43,0.666,0.713,0.341,0.601,0.520,0.178,1.407
Jordan,Middle East and North Africa,4.395,0.062,4.516,4.273,9.182,0.767,67.000,0.755,-0.167,0.705,2.43,0.890,0.685,0.583,0.455,0.079,0.150,1.553
Chad,Sub-Saharan Africa,4.355,0.094,4.540,4.171,7.364,0.619,48.478,0.579,0.041,0.807,2.43,0.255,0.353,0.000,0.240,0.215,0.084,3.209
Sri Lanka,South Asia,4.325,0.066,4.454,4.196,9.470,0.827,67.299,0.841,0.079,0.863,2.43,0.990,0.820,0.593,0.559,0.239,0.049,1.075
Swaziland,Sub-Saharan Africa,4.308,0.071,4.448,4.168,9.065,0.770,50.833,0.647,-0.185,0.708,2.43,0.849,0.693,0.074,0.323,0.067,0.147,2.155
Comoros,Sub-Saharan Africa,4.289,0.084,4.454,4.123,8.031,0.626,57.349,0.548,0.082,0.781,2.43,0.488,0.367,0.279,0.202,0.241,0.101,2.610
Egypt,Middle East and North Africa,4.283,0.045,4.371,4.195,9.367,0.750,61.998,0.749,-0.182,0.795,2.43,0.954,0.647,0.426,0.446,0.069,0.092,1.648
Ethiopia,Sub-Saharan Africa,4.275,0.051,4.374,4.175,7.694,0.764,59.000,0.752,0.082,0.761,2.43,0.370,0.679,0.331,0.451,0.241,0.114,2.089
Mauritania,Sub-Saharan Africa,4.227,0.070,4.365,4.090,8.542,0.795,57.161,0.561,-0.106,0.731,2.43,0.666,0.749,0.273,0.218,0.119,0.133,2.069
Madagascar,Sub-Saharan Africa,4.208,0.072,4.349,4.068,7.396,0.686,59.305,0.552,-0.005,0.803,2.43,0.266,0.503,0.341,0.207,0.185,0.087,2.620
Togo,Sub-Saharan Africa,4.107,0.077,4.258,3.956,7.362,0.569,54.914,0.619,0.032,0.772,2.43,0.254,0.239,0.203,0.289,0.209,0.107,2.806
Zambia,Sub-Saharan Africa,4.073,0.069,4.209,3.938,8.145,0.708,55.809,0.782,0.061,0.823,2.43,0.528,0.552,0.231,0.487,0.227,0.074,1.975
Sierra Leone,Sub-Saharan Africa,3.849,0.077,4.001,3.698,7.434,0.630,51.651,0.717,0.084,0.866,2.43,0.279,0.377,0.100,0.408,0.243,0.047,2.396
India,South Asia,3.819,0.026,3.869,3.769,8.755,0.603,60.633,0.893,0.089,0.774,2.43,0.741,0.316,0.383,0.622,0.246,0.106,1.405

## Delete rows with named index:

In [15]:
coin.drop(3)

,SNo,Name,Symbol,Date,Month,Year,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,4/29/2013 23:59,4,2013,147.49,134.00,134.44,144.54,0,1603768865
1,2,Bitcoin,BTC,4/30/2013 23:59,4,2013,146.93,134.05,144.00,139.00,0,1542813125
2,3,Bitcoin,BTC,5/1/2013 23:59,5,2013,139.89,107.72,139.00,116.99,0,1298954594
4,5,Bitcoin,BTC,5/3/2013 23:59,5,2013,108.13,79.10,106.25,97.75,0,1085995169

In [20]:
# To delete multiple rows with index.
coin.drop([2,4])

,SNo,Name,Symbol,Date,Month,Year,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,4/29/2013 23:59,4,2013,147.49,134.00,134.44,144.54,0,1603768865
1,2,Bitcoin,BTC,4/30/2013 23:59,4,2013,146.93,134.05,144.00,139.00,0,1542813125
3,4,Bitcoin,BTC,5/2/2013 23:59,5,2013,125.60,92.28,116.38,105.21,0,1168517495

## Delete rows that are not numerically indexed

In [23]:
countries

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [24]:
countries.drop(countries.index[3:142])

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Haiti,Latin America and Caribbean,3.615,0.173,3.953,3.276,7.477,0.540,55.700,0.593,0.422,0.721,2.43,0.294,0.173,0.227,0.257,0.463,0.139,2.060
Malawi,Sub-Saharan Africa,3.600,0.092,3.781,3.419,6.958,0.537,57.948,0.780,0.038,0.729,2.43,0.113,0.168,0.298,0.484,0.213,0.134,2.190
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [27]:
countries.drop(countries.index[10:])
# This drops everything after 10th indexed items.
# Only prints 0-10 items

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.3,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
Sweden,Western Europe,7.363,0.036,7.433,7.293,10.867,0.934,72.7,0.945,0.086,0.237,2.43,1.478,1.062,0.763,0.685,0.244,0.448,2.683
Luxembourg,Western Europe,7.324,0.037,7.396,7.252,11.647,0.908,72.6,0.907,-0.034,0.386,2.43,1.751,1.003,0.760,0.639,0.166,0.353,2.653
New Zealand,North America and ANZ,7.277,0.040,7.355,7.198,10.643,0.948,73.4,0.929,0.134,0.242,2.43,1.400,1.094,0.785,0.665,0.276,0.445,2.612
Austria,Western Europe,7.268,0.036,7.337,7.198,10.906,0.934,73.3,0.908,0.042,0.481,2.43,1.492,1.062,0.782,0.640,0.215,0.292,2.784

## Adding Static Columns

We want a column name of 'Country' and value to be 'United States'

syntax:
       df["Col_name"] = "name"

In [33]:
state = pd.read_csv("state_pops.csv")
state["country"] = "United States"

In [35]:
state.head()

  state  year  population        country
0    AL  2012   4817528.0  United States
1    AL  2010   4785570.0  United States
2    AL  2011   4801627.0  United States
3    AL  2009   4757938.0  United States
4    AL  2013   4833722.0  United States

## Change position of columns

syntax: 
        df.insert(2,"col_name","value)
        here 2 is position

In [37]:
state = pd.read_csv("state_pops.csv")
state.insert(2,"Country","United States")

In [39]:
state.head()

  state  year        Country  population
0    AL  2012  United States   4817528.0
1    AL  2010  United States   4785570.0
2    AL  2011  United States   4801627.0
3    AL  2009  United States   4757938.0
4    AL  2013  United States   4833722.0

We can also dynamically allocate a value from different column

In [41]:
ufo = pd.read_csv("nuforc_reports.csv")
ufo.head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12T18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22T18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
2,I woke up late in the afternoon 3:30-4pm. I we...,NaN,NaN,NaN,NaN,NaN,Occurred : 4/1/2019 15:45 (Entered as : April...,http://www.nuforc.org/webreports/145/S145556.html,I woke up late in the afternoon 3:30-4pm. I w...,NaN,NaN,NaN
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17T02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
4,"In Peoria Arizona, I saw a cigar shaped craft ...",Peoria,NY,2009-03-15T18:00:00,cigar,2 minutes,Occurred : 3/15/2009 18:00 (Entered as : 03/1...,http://www.nuforc.org/webreports/145/S145723.html,"In Peoria, Arizona, I saw a cigar shaped craft...",2019-04-18T00:00:00,NaN,NaN

In [43]:
ufo.insert(2,"site_location",ufo["state"])
# This prints a new column at 2nd position with new name site_location
# But, the values are just copy of 'state' column

In [45]:
ufo.head(3)

,summary,city,site_location,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,VA,2019-12-12T18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,CT,2019-03-22T18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
2,I woke up late in the afternoon 3:30-4pm. I we...,NaN,NaN,NaN,NaN,NaN,NaN,Occurred : 4/1/2019 15:45 (Entered as : April...,http://www.nuforc.org/webreports/145/S145556.html,I woke up late in the afternoon 3:30-4pm. I w...,NaN,NaN,NaN

## Creating new dynamic column

In [48]:
titanic = pd.read_csv("titanic.csv")
titanic.head()
# We can make new column by adding multiple columns

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [49]:
titanic["total_relatives"] = titanic["sibsp"] + titanic["parch"]

In [50]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,total_relatives
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",0
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",3
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",3
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",3
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",3

In [51]:
# By default, it always print at the last column to print it to desired column
titanic = pd.read_csv("titanic.csv")
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [52]:
titanic.insert(2,"total_relative",titanic["sibsp"]+titanic["parch"])

In [54]:
titanic.head()

,pclass,survived,total_relative,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,0,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,3,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,3,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,3,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,3,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

Create a new column "price_sqft" that is calculated by :
    price_sqft = price/sqft_living

In [55]:
houses = pd.read_csv("kc_house_data.csv")
houses.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [56]:
houses["price_sqft"] = houses["price"]/houses["sqft_living"]

In [57]:
houses.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_sqft
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,188.050847
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,209.338521
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,233.766234
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,308.163265
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,303.571429